### ISSUE TITLE
Is that possible to support loading in-memory structures from files?

### ISSUE THREAD

**Issue by Zxilly** [yassinebenaid/godump#49]
like `encoding/gob` did, but supports private field. I'd like to use this feature to implement something like snapshot testing.

**Comment by yassinebenaid** [comment]
It's doable, But unfortunately, That's out of the scope of this library.
`godump` is all about generating human readable representation out of arbitrary data structures. We're trying to do one thing, And do it well.

However, That's a great idea. I thing it would be very useful in contexts like the one you've mentioned. Hopefully, we can implement it later  when more users are interested in this feature.

I advise you to check this library  https://github.com/gkampitakis/go-snaps, I think it offers exactly what you want.

Thanks.
